package com.miaoshaproject.dao;

import com.miaoshaproject.dataobject.ItemDo;

import java.util.List;

public interface ItemDoMapper {

    //按销量倒序查询所有商品
    List<ItemDo> listItem();


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbg.generated Wed Dec 19 15:54:42 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbg.generated Wed Dec 19 15:54:42 CST 2018
     */
    int insert(ItemDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbg.generated Wed Dec 19 15:54:42 CST 2018
     */
    int insertSelective(ItemDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbg.generated Wed Dec 19 15:54:42 CST 2018
     */
    ItemDo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbg.generated Wed Dec 19 15:54:42 CST 2018
     */
    int updateByPrimaryKeySelective(ItemDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbg.generated Wed Dec 19 15:54:42 CST 2018
     */
    int updateByPrimaryKey(ItemDo record);
}