package com.miaoshaproject.dao;

import com.miaoshaproject.dataobject.UserPasswordDo;
import org.apache.ibatis.annotations.Mapper;

@Mapper
public interface UserPasswordDoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_password
     *
     * @mbg.generated Tue Dec 11 15:39:17 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_password
     *
     * @mbg.generated Tue Dec 11 15:39:17 CST 2018
     */
    int insert(UserPasswordDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_password
     *
     * @mbg.generated Tue Dec 11 15:39:17 CST 2018
     */
    int insertSelective(UserPasswordDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_password
     *
     * @mbg.generated Tue Dec 11 15:39:17 CST 2018
     */
    UserPasswordDo selectByPrimaryKey(Integer id);

    //根据用户id查询
    UserPasswordDo selectByUserId(Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_password
     *
     * @mbg.generated Tue Dec 11 15:39:17 CST 2018
     */
    int updateByPrimaryKeySelective(UserPasswordDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_password
     *
     * @mbg.generated Tue Dec 11 15:39:17 CST 2018
     */
    int updateByPrimaryKey(UserPasswordDo record);
}